### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by driusan** [sirnewton01/ghfs#10]
I'm getting the error

```
# github.com/sirnewton01/ghfs/dynamic
dynamic/server.go:369:5: undefined: protocol.Debug
dynamic/server.go:370:8: undefined: protocol.DebugServer
```

when trying to build on a Mac.

**Comment by sirnewton01** [comment]
Thanks, I'm using some items from a pending PR on the Harvey-OS/ninep repo. I'll bring in this functionality in until whenever/if ever they merge my PR.

**Comment by sirnewton01** [comment]
Okay, this should be fixed now.
